# Use the official Python image from the Docker Hub
FROM python:3.12-slim

RUN apt-get clean
RUN apt-get update
RUN apt-get install -y git

# Install required dependencies for JDK, Node.js, and general system utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    tar \
    xz-utils \
    g++ \
    ca-certificates \
    gnupg \
    dirmngr \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

# Download and install JDK 23.0.1
RUN curl -fsSL https://download.java.net/java/GA/jdk23.0.1/c28985cbf10d4e648e4004050f8781aa/11/GPL/openjdk-23.0.1_linux-x64_bin.tar.gz \
    | tar -xz -C /usr/local \
    && ln -s /usr/local/jdk-23.0.1 /usr/local/java

# Set Java environment variable
ENV JAVA_HOME=/usr/local/java
ENV PATH="$JAVA_HOME/bin:$PATH"

# Download and install Node.js v22.14.0
RUN curl -fsSL https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz \
    | tar -xJ -C /usr/local \
    && ln -s /usr/local/node-v22.14.0-linux-x64 /usr/local/node

# Set Node.js environment variables
ENV NODE_HOME=/usr/local/node
ENV PATH="$NODE_HOME/bin:$PATH"

# Verify installation
RUN node -v && npm -v

# Set the working directory
WORKDIR /app

# Copy and install python dependencies
COPY requirements.txt .
COPY requirements_dev.txt .


RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements_dev.txt

